version: "3"
services:
  server:
    container_name: server
    # build:
    #   context: ./server
    # env_file:
    #   - ./server/.env
    # volumes:
    #   - ./server:/usr/src/connect
    image: dockerx2000/connect_server
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
    networks:
      - connect

  client:
    container_name: client
    # build:
    #   context: ./client
    # volumes:
    #   - ./client:/usr/src/connect
    image: dockerx2000/connect_client
    env_file:
      - ./client/src/.env
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - connect

networks:
  connect:
    driver: bridge
