name: Build and Deploy

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: build

    env:
      JWT_SECRET: ${ { secrets.JWT_SECRET } }
      KAFKA_BROKER: ${ { secrets.KAFKA_BROKER } }
      KAFKA_PASSWORD: ${ { secrets.KAFKA_PASSWORD } }
      KAFKA_USERNAME: ${ { secrets.KAFKA_USERNAME } }
      MONGO_URI: ${ { secrets.MONGO_URI } }
      PROD_CLIENT_URL: ${ { secrets.PROD_CLIENT_URL } }
      REACT_APP_CLOUDINARY_API: ${ { secrets.REACT_APP_CLOUDINARY_API } }
      REACT_APP_CLOUD_NAME: ${ { secrets.REACT_APP_CLOUD_NAME } }
      REACT_APP_UPLOAD_PRESET: ${ { secrets.REACT_APP_UPLOAD_PRESET } }
      REDIS_HOST: ${ { secrets.REDIS_HOST } }
      REDIS_PASSWORD: ${ { secrets.REDIS_PASSWORD } }
      REDIS_USERNAME: ${ { secrets.REDIS_USERNAME } }

    steps:
      - name: pulling git repo
        uses: actions/checkout@v4

      - name: installing nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"

      - name: install client
        working-directory: ./client
        run: npm install

      - name: install server
        working-directory: ./server
        run: npm install
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Build and push client
        id: docker_build_client
        uses: docker/build-push-action@v2
        with:
          context: ./client
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags:  dockerx2000/connect-client:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Build and push server 
        id: docker_build_server
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags:  dockerx2000/connect-server:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache