name: Build and Deploy

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: build

    env:
      JWT_SECRET: ${ { secrets.JWT_SECRET } }
      KAFKA_BROKER: ${ { secrets.KAFKA_BROKER } }
      KAFKA_PASSWORD: ${ { secrets.KAFKA_PASSWORD } }
      KAFKA_USERNAME: ${ { secrets.KAFKA_USERNAME } }
      MONGO_URI: ${ { secrets.MONGO_URI } }
      PROD_CLIENT_URL: ${ { secrets.PROD_CLIENT_URL } }
      REACT_APP_CLOUDINARY_API: ${ { secrets.REACT_APP_CLOUDINARY_API } }
      REACT_APP_CLOUD_NAME: ${ { secrets.REACT_APP_CLOUD_NAME } }
      REACT_APP_UPLOAD_PRESET: ${ { secrets.REACT_APP_UPLOAD_PRESET } }
      REDIS_HOST: ${ { secrets.REDIS_HOST } }
      REDIS_PASSWORD: ${ { secrets.REDIS_PASSWORD } }
      REDIS_USERNAME: ${ { secrets.REDIS_USERNAME } }

    steps:
      - name: pulling git repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push client
        uses: docker/build-push-action@v5
        with:
          context: ./client
          push: true
          tags: dockerx2000/connect_client:latest
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Build and push server
        uses: docker/build-push-action@v5
        with:
          context: ./server
          push: true
          tags: dockerx2000/connect_server:latest
          cache-to: type=local,dest=/tmp/.buildx-cache
      
      - name: Build and push nginx
        uses: docker/build-push-action@v5
        with:
          context: ./nginx
          push: true
          tags: dockerx2000/connect_nginx:latest
          cache-to: type=local,dest=/tmp/.buildx-cache
